global using GoTopFloatingButtonList.Helpers;
global using GoTopFloatingButtonList.Models;
global using GoTopFloatingButtonList.ViewModels;
global using GoTopFloatingButtonList.Views.Pages;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
